spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
  
#spring:
  #datasource:
    #url: jdbc:mysql://localhost:3306/userDb
    #url: jdbc:mysql://localhost:3306/springbatch26
    #username: app-root
    #username: root
    #password: root123
    #password: root
  #jpa:
    #hibernate:
      #ddl-auto: update
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #show-sql: true
#server:
  #port: 8089
  
